[package]
name = "rv-plic"
version = "0.1.0"
edition = "2018"
authors = ["Campbell He"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
volatile-register = "0.2"
