[package]
name = "rv-plic"
version = "0.5.0"
edition = "2018"
authors = ["Campbell He (duskmoon)"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
ctrl_1ffffc = []

xuantie_c906 = ["ctrl_1ffffc"]

[dependencies]
vcell = "0.1"
